CREATE TABLE `Instance` (
  `AccountId` varchar(12) NOT NULL,
  `instanceId` varchar(19) NOT NULL,
  `amiLaunchIndex` tinyint(4) DEFAULT '0',
  `architecture` varchar(6) NOT NULL DEFAULT 'x86_64',
  `blockDevices_orig` json DEFAULT NULL,
  `blockDevices_new` json DEFAULT NULL,
  `clientToken` varchar(24) DEFAULT 'NONE',
  `ebsOptimized` tinyint(1) DEFAULT '0',
  `hypervisor` varchar(3) DEFAULT 'xen',
  `iamInstanceProfile` varchar(45) DEFAULT NULL,
  `instanceLifecycle` varchar(9) DEFAULT NULL,
  `instanceType` varchar(11) NOT NULL,
  `kernelId` varchar(10) DEFAULT NULL,
  `keyName` varchar(24) DEFAULT NULL,
  `launchTime` datetime DEFAULT NULL,
  `monitoring` json DEFAULT NULL,
  `networkInterfaceSet` json DEFAULT NULL,
  `placement` varchar(20) DEFAULT NULL,
  `platform` varchar(7) DEFAULT NULL,
  `privateDnsName_orig` varchar(255) NOT NULL,
  `privateDnsName_new` varchar(255) DEFAULT NULL,
  `privateIpAddress_orig` varchar(15) NOT NULL,
  `privateIpAddress_new` varchar(15) DEFAULT NULL,
  `productCodes` json DEFAULT NULL,
  `dnsName_orig` varchar(255) DEFAULT NULL,
  `dnsName_new` varchar(255) DEFAULT NULL,
  `ipAddress_orig` varchar(15) DEFAULT NULL,
  `ipAddress_new` varchar(15) DEFAULT NULL,
  `ramdiskId` varchar(10) DEFAULT NULL,
  `rootDeviceName` varchar(10) NOT NULL,
  `rootDeviceType` varchar(14) NOT NULL DEFAULT 'ebs',
  `groupSet` json NOT NULL,
  `sourceDestCheck` tinyint(1) DEFAULT NULL,
  `spotInstanceRequestId` varchar(20) DEFAULT NULL,
  `sriovNetSupport` tinyint(1) DEFAULT '0',
  `instanceState` varchar(8) DEFAULT NULL,
  `stateReason` varchar(1) DEFAULT NULL,
  `reason` tinyint(2) DEFAULT NULL,
  `subnetId` varchar(15) NOT NULL,
  `tagSet` json DEFAULT NULL,
  `virtualizationType` varchar(11) DEFAULT NULL,
  `vpcId` varchar(12) NOT NULL,
  PRIMARY KEY (`instanceId`)
)
